# Functions
source ~/.dotfiles/shell/functions.sh

# Allow local customizations in the shell_local_before file
if [ -f ~/.dot_local/shell_local_before ]; then
    source ~/.dot_local/shell_local_before
fi

# Allow local customizations in the zshrc_local_before file
if [ -f ~/.dot_local/zshrc_local_before ]; then
    source ~/.dot_local/zshrc_local_before
fi

# Settings
source ~/.dotfiles/zsh/settings.zsh

# Bootstrap
source ~/.dotfiles/shell/bootstrap.sh

# External settings
source ~/.dotfiles/shell/external.sh

# Aliases
source ~/.dotfiles/shell/aliases.sh

# Custom prompt
source ~/.dotfiles/zsh/prompt.zsh

# Plugins 
source ~/.dotfiles/zsh/plugins.zsh

# Crontab
source ~/.dotfiles/crontab/cron.sh

# Allow local customizations in the shell_local_after file
if [ -f ~/.dot_local/shell_local_after ]; then
    source ~/.dot_local/shell_local_after
fi

# Allow local customizations in the zshrc_local_after file
if [ -f ~/.dot_local/zshrc_local_after ]; then
    source ~/.dot_local/zshrc_local_after
fi
