# Functions
source ~/.dotfiles/shell/functions.sh

# Allow local customizations in the shell_local_before file
if [ -f ~/.dot_local/shell_local_before ]; then
    source ~/.dot_local/shell_local_before
fi

# Allow local customizations in the bashrc_local_before file
if [ -f  ~/.dot_local/bashrc_local_before ]; then
    source ~/.dot_local/bashrc_local_before
fi

# Settings
source ~/.dotfiles/bash/settings.bash

# Bootstrap
source ~/.dotfiles/shell/bootstrap.sh

# External settings
source ~/.dotfiles/shell/external.sh

# Aliases
source ~/.dotfiles/shell/aliases.sh

# Custom prompt
source ~/.dotfiles/bash/prompt.bash

# Plugins
source ~/.dotfiles/bash/plugins.bash

# Crontab
source ~/.dotfiles/crontab/cron.sh

# Allow local customizations in the shell_local_after file
if [ -f ~/.dot_local/shell_local_after ]; then
    source ~/.dot_local/shell_local_after
fi

# Allow local customizations in the bashrc_local_after file
if [ -f ~/.dot_local/bashrc_local_after ]; then
    source ~/.dot_local/bashrc_local_after
fi
